### ISSUE TITLE
Separate and expand the `guix home` as the home manager

### ISSUE THREAD

**Issue by c4dr01d** [abcdw/rde#19]
Hi, I just transfer my home environment from the Julien Lepiller's guix-home-manager, I feel very confortable working on rde. I don't know if the author have any idea split guix home out of rde and expand it to a experimental guix-home-manager. :)

**Comment by abcdw** [comment]
> Hi, I just transfer my home environment from the Julien Lepiller's
> guix-home-manager, I feel very confortable working on rde. I don't know
> if the author have any idea split guix home out of rde and expand it to
> a experimental guix-home-manager. :)

Hi!) I plan to move `guix home` to guix itself [fn:1] and continue
development as a part of guix, but before exposing it to a larger number
of users I have to be sure that it won't require any breaking changes.
We work on few more essential home-services, cleaning up some stuff and
making naming more consistent. After that we will invite early adopters
to use it, test it and report their experience. Hope to make it happen
in the next few weeks. The development happens on sr.ht and you can track
the progress and read announcements by subscribing on mailing list. [fn:2]

Just after that I plan to start moving `guix home` from rde to guix, but
don't know how much time it will take.

When `guix home` will be moved to guix, rde would be an opinionated
configuration based on `guix system/home` for developers and a set of
other useful tools and packages.

Hope now you see the overall direction of the project.

P.S. Please prefer rde-discuss mailing list to github issues.

* Footnotes

[fn:1] ***@***.***/msg56862.html

[fn:2] https://sr.ht/~abcdw/rde/lists

-- 
Best regards,
Andrew Tropin

**Comment by abcdw** [comment]
[fn:1] https://www.mail-archive.com/guix-devel@gnu.org/msg56862.html

**Comment by c4dr01d** [comment]
@abcdw What the format to subscribe the list? like what title is and what content is. :)

**Comment by abcdw** [comment]
> @abcdw What the format to subscribe the list? like what title is and
> what content is. :)

Not sure what you mean.
https://man.sr.ht/lists.sr.ht/#email-controls

If you talk about the subject and body of email for subscription - it can be
any, even empty. The message won't go to any mailing list.


-- 
Best regards,
Andrew Tropin
