### ISSUE TITLE
Incorrect module?

### ISSUE THREAD

**Issue by Tass0sm** [abcdw/rde#21]
Thanks for making Guix Home. I enjoy using it a lot.

When I try to pull from the rde channel, it fails to build and says "no code for module (gnu home services configuration)", which is used in emacs.scm and home-services-utils.scm. I can't find this module in upstream guix. Does it still exist somewhere else?

**Comment by abcdw** [comment]
Thank you for letting me know, I somehow resolved the issues caused by upstream updates, will cleanup it later.
