### ISSUE TITLE
ISO frozen after "Please wait while gathering entropy"

### ISSUE THREAD

**Issue by yusi1** [abcdw/rde#25]
Hi! 

I really like your project and I am wanting to try out the ISO, but when I boot the ISO, it gets stuck on "Please wait while gathering entropy to generate the keypair" and swaywm does not appear.

My PC has an AMD RX 580 GPU.

**Comment by abcdw** [comment]
On 2023-11-18 01:05, Yusef Aslam wrote:

> Hi! 
>

Hi Yusef!

> I really like your project and I am wanting to try out the ISO, but
> when I boot the ISO, it gets stuck on "Please wait while gathering
> entropy to generate the keypair" and swaywm does not appear.

Thank you for the kind words.

Sway will be started only after you login into tty with guest/guest
credentials.

>
> My PC has an AMD RX 580 GPU.

Unfortunatelly, I don't have this hardware at my disposal and can't try,
but you can write to #tropin or #guix channel on libera.chat and to
rde-discuss or bug-guix mailing lists, report the issue and ask if
somebody has the same problem.

https://lists.sr.ht/~abcdw/rde-discuss
https://issues.guix.gnu.org/

-- 
Best regards,
Andrew Tropin

**Comment by yusi1** [comment]
> On 2023-11-18 01:05, Yusef Aslam wrote: Hi!
> Hi Yusef!

> Thank you for the kind words. Sway will be started only after you login into tty with guest/guest credentials.

Okay got it.

> Unfortunatelly, I don't have this hardware at my disposal and can't try, but you can write to #tropin or #guix channel on libera.chat and to rde-discuss or bug-guix mailing lists, report the issue and ask if somebody has the same problem. https://lists.sr.ht/~abcdw/rde-discuss https://issues.guix.gnu.org/

Okay thanks, I will report the issue to them mailing lists.
