### ISSUE TITLE
How do I install this as an ISO

### ISSUE THREAD

**Issue by imadnyc** [abcdw/rde#26]
Sorry for the noob question, Guix is super confusing to me. I see that there's a file in here that tells you how to install Guix, but I don't see any Guix commands? And how do I add my own configuration? 

I'd like
    - to know how to install this from the live iso without going through Guix installer
    - How do use this repo on a fresh guix install
    - If I install it as a channel, what do I do with it?

**Comment by abcdw** [comment]
The good starting points to grasp a bit more of guix and guile basic are guix manual, scheme primer and System Crafters videos on youtube.

Primary places, where RDE community is hanging out are here: https://trop.in/rde/manual#Communication-1
